# fly.toml app configuration file generated for crypto-rebalancer on 2024-01-17T21:01:10+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crypto-rebalancer"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
